export const CLOSE_REPORT = "CLOSE_REPORT";
export const OPEN_REPORT = "OPEN_REPORT";
export const SWITCH_SECTION = "SWITCH_SECTION";
//
export const FETCH_MEMBERNUMBER = "FETCH_MEMBERNUMBER";
export const FETCH_POSTINGNUMBER = "FETCH_POSTINGNUMBER";
export const FETCH_TICKETNUMBER = "FETCH_TICKETNUMBER";
export const FETCH_ADMINUSER = "FETCH_ADMINUSER";
//
export const CHANGE_EMAIL = "CHANGE_EMAIL";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const UPDATE_USERINFO = "UPDATE_USERINFO";
export const UPDATE_ADMININFO = "UPDATE_ADMININFO";
//
export const DELETE_TICKET = "DELETE_TICKET";
export const DELETE_USER = "DELETE_USER";
export const CREATE_TICKET = "CREATE_TICKET";
//
export const DELETE_POSTING = "DELETE_POSTING";
export const UPDATE_POSTING = "UPDATE_POSTING";
//
export const CREATE_REVIEW_AS_LENDER = "CREATE_REVIEW_AS_LENDER";
export const CREATE_REVIEW_AS_BORROWER = "CREATE_REVIEW_AS_LENDER";
export const UPDATE_REVIEW = "UPDATE_REVIEW"
//
export const CREATE_TRANSACTION = "CREATE_TRANSACTION";
export const DECLINE_TRANSACTION = "DECLINE_TRANSACTION";
export const APPROVE_TRANSACTION = "APPROVE_TRANSACTION";
export const DELETE_TRANSACTION = "DELETE_TRANSACTION";
export const RETURN_TRANSACTION = "RETURN_TRANSACTION";
//
export const DELETE_FOLLOW = "DELETE_FOLLOW";
export const CREATE_FOLLOW = "CREATE_FOLLOW";

