export const SWITCH_SECTION = "SWITCH_SECTION";
// FETCH
export const FETCH_ALLPOSTINGS = "FETCH_ALLPOSTINGS";
export const FETCH_ALLTICKETS = "FETCH_ALLTICKETS";
export const FETCH_ADMINUSER = "FETCH_ADMINUSER";
export const FETCH_ALLUSERS = "FETCH_ALLUSERS";
export const FETCH_USER = "FETCH_USER";
export const FETCH_ALLUSERBORROWINGS = "FETCH_ALLUSERBORROWINGS";
export const FETCH_ALLUSERLENDINGS = "FETCH_ALLUSERLENDINGS";
export const FETCH_USERFOLLOWINGS = "FETCH_USERFOLLOWINGS";
export const FETCH_USERFOLLOWERS = "FETCH_USERFOLLOWERS";
export const FETCH_USERREADINGLIST = "FETCH_USERREADINGLIST"
export const AUTHENTICATE = "AUTHENTICATE";
export const FETCH_LOGGEDINUSERFOLLOWINGS = "FETCH_LOGGEDINUSERFOLLOWINGS";
// USERINFO
export const UPDATE_USERINFO = "UPDATE_USERINFO";
export const UPDATE_ADMININFO = "UPDATE_ADMININFO";
// REPORT
export const DELETE_TICKET = "DELETE_TICKET";
export const CREATE_TICKET = "CREATE_TICKET";
export const CLOSE_REPORT = "CLOSE_REPORT";
export const OPEN_REPORT = "OPEN_REPORT";
// POSTINGS
export const DELETE_POSTING = "DELETE_POSTING";
export const UPDATE_POSTING = "UPDATE_POSTING";
export const DELETE_POSTING_FROM_ADMIN = "DELETE_POSTING_FROM_ADMIN";
// REVIEW
export const CREATE_REVIEW_AS_LENDER = "CREATE_REVIEW_AS_LENDER";
export const CREATE_REVIEW_AS_BORROWER = "CREATE_REVIEW_AS_LENDER";
export const UPDATE_REVIEW = "UPDATE_REVIEW";
export const FETCH_REVIEWSUSERRECEIVED = "FETCH_REVIEWSUSERRECEIVED";
export const FETCH_REVIEWSUSERGAVE = "FETCH_REVIEWSUSERGAVE";
export const DELETE_REVIEW = "DELETE_REVIEW";
// TRANSACTION
export const CREATE_TRANSACTION = "CREATE_TRANSACTION";
export const DECLINE_TRANSACTION = "DECLINE_TRANSACTION";
export const APPROVE_TRANSACTION = "APPROVE_TRANSACTION";
export const DELETE_TRANSACTION = "DELETE_TRANSACTION";
export const RETURN_TRANSACTION = "RETURN_TRANSACTION";
// FOLLOW
export const DELETE_USERFOLLOWING = "DELETE_USERFOLLOWING";
export const CREATE_USERFOLLOWING = "CREATE_USERFOLLOWING";
export const DELETE_USERFOLLOWER = "DELETE_USERFOLLOWER";
export const CREATE_USERFOLLOWER = "CREATE_USERFOLLOWER";
export const ADD_TO_LOGGEDINUSERFOLLOWINGS = "ADD_TO_LOGGEDINUSERFOLLOWINGS";
export const DELETE_FROM_LOGGEDINUSERFOLLOWINGS = "DELETE_FROM_LOGGEDINUSERFOLLOWINGS";
// READINGLIST
export const DELETE_FROMREADINGLIST = "DELETE_FROMREADINGLIST";
export const ADD_BOOK = "ADD_BOOK";
// Email Subscriptions
export const FIND_ALL_SUBSCRIPTIONS = "FIND_ALL_SUBSCRIPTIONS";
export const UNSUBSCRIBE = "UNSUBSCRIBE";
