export const FIND_BOOK = "FIND_BOOK";
export const UPDATE_BOOK = "UPDATE_BOOK";
export const POST_A_BOOK = "POST_A_BOOK";
export const FIND_ALL_BORROWING_OPTIONS = "FIND_ALL_BORROWING_OPTIONS";
export const START_A_BORROWING_REQUEST = "START_A_BORROWING_REQUEST";
export const CANCEL_BORROWING = "CANCEL_BORROWING";
export const SUBMIT_A_BORROWING_REQUEST = "SUBMIT_A_BORROWING_REQUEST";