export const UPDATE_USER = "UPDATE_USER";

export const ADD_TO_READING_LIST = "ADD_TO_READING_LIST";
export const GET_FOLLOWINGS_READING_LIST = "GET_FOLLOWINGS_READING_LIST";

export const FIND_ALL_USERS = "FIND_ALL_USERS";
export const FIND_USER_BY_ID = "FIND_USER_BY_ID";
